language: python
dist: focal  
python:
  - "3.10"   

before_install:
  - sudo apt-get update

install:
  - python -m pip install --upgrade pip
  - python -m pip install telebot flask pytz psutil aiogram pymongo aiohttp python-telegram-bot && chmod +x bgmi

script:
  - python3 main.py
